# Generated by Django 5.0.1 on 2024-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='Abc', max_length=500),
            preserve_default=False,
        ),
    ]
