# Generated by Django 5.0.1 on 2024-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
